#!/bin/sh


# StoRM Frontend start script

export GRIDMAPDIR=/etc/grid-security/gridmapdir
export GRIDMAP=/etc/grid-security/grid-mapfile
CONFIGURATION_FILE=/etc/storm/frontend-server/storm-frontend-server.conf

ARC=`/bin/uname -m`
if [ ${ARC} = x86_64 ] ; then
      export LD_LIBRARY_PATH="/usr/lib64/storm:${LD_LIBRARY_PATH}"
    else
      export LD_LIBRARY_PATH="/usr/lib/storm:${LD_LIBRARY_PATH}"
fi

export X509_USER_CERT=/etc/grid-security/storm/hostcert.pem
export X509_USER_KEY=/etc/grid-security/storm/hostkey.pem


mkdir -p /var/log/storm
chown storm:storm /var/log/storm

su -m -s "/bin/bash" -c "/usr/sbin/storm-frontend-server -d -c $CONFIGURATION_FILE >>/var/log/storm/storm-frontend-server.log 2>&1" storm

