FROM    centos:centos5

RUN \
  rpm --import http://mirror.centos.org/centos/5/os/x86_64/RPM-GPG-KEY-CentOS-5 && \
  rpm -Uvh http://yum.puppetlabs.com/puppetlabs-release-el-5.noarch.rpm && \
  yum clean all && \
  yum -y update && \
  yum --enablerepo=centosplus install -y epel-release redhat-lsb wget git tar puppet && \
  puppet module install --force maestrodev-wget && \
  puppet module install --force gini-archive && \
  puppet module install --force puppetlabs-stdlib
